### ISSUE TITLE
'GPU tensor on CPU index not allowed'

### ISSUE THREAD

**Issue by zuoweic** [GradientSpaces/LoopSplat#10]
Hi, thank you for your great work, when I run your code on TUM desk and desk2 datasets, this error occurs at the 337th frame and I have no idea how to fix it.
My computer is Ubuntu20.04 and the conda environment is the same with your environment.yml and requirements.txt. And my computer has 4 GPUs.
My laptop (which only has 1 GPU) doesn't have this problem (but my laptop has out of memory error), so I think maybe the error is related to the GPU? 
Tracking frame 337
iter: 0, color_loss: 16969.30469, depth_loss: 3585.02588 , cam_quad_err: 0.02043, cam_trans_err: 0.03461
iter: 20, color_loss: 20583.98438, depth_loss: 3789.31494 , cam_quad_err: 0.02352, cam_trans_err: 0.03011
iter: 40, color_loss: 13384.35742, depth_loss: 3478.19409 , cam_quad_err: 0.02321, cam_trans_err: 0.03211
iter: 60, color_loss: 12848.65625, depth_loss: 3770.62085 , cam_quad_err: 0.02316, cam_trans_err: 0.03164
iter: 80, color_loss: 12737.18652, depth_loss: 3702.93359 , cam_quad_err: 0.02318, cam_trans_err: 0.03172
iter: 100, color_loss: 12705.96484, depth_loss: 3629.77930 , cam_quad_err: 0.02325, cam_trans_err: 0.03162
iter: 120, color_loss: 12808.74121, depth_loss: 3631.06885 , cam_quad_err: 0.02327, cam_trans_err: 0.03165
iter: 140, color_loss: 12843.27344, depth_loss: 3623.10913 , cam_quad_err: 0.02327, cam_trans_err: 0.03165
iter: 160, color_loss: 12866.03027, depth_loss: 3622.38574 , cam_quad_err: 0.02327, cam_trans_err: 0.03167
iter: 180, color_loss: 12892.30664, depth_loss: 3618.48291 , cam_quad_err: 0.02327, cam_trans_err: 0.03168
frame_id: 337, cam_quad_err: 0.02320, cam_trans_err: 0.03163 , cam_quad_err: 0.02320, cam_trans_err: 0.03163

New submap at 337

Detecting loop closures ...
0it [00:01, ?it/s]
Traceback (most recent call last):
  File "/home/y/4tdisk/LoopSplat/run_slam.py", line 109, in <module>
    gslam.run()
  File "/home/y/4tdisk/LoopSplat/src/entities/gaussian_slam.py", line 238, in run
    lc_output = self.loop_closer.loop_closure(self.estimated_c2ws)
  File "/home/y/4tdisk/LoopSplat/src/entities/lc.py", line 282, in loop_closure
    pose_graph, odometry_edges, loop_edges = self.construct_pose_graph(final)
  File "/home/y/4tdisk/LoopSplat/src/entities/lc.py", line 237, in construct_pose_graph
    reg_dict = self.pairwise_registration(submap_list[source_id], submap_list[target_id], "gs_reg")
  File "/home/y/4tdisk/LoopSplat/src/entities/lc.py", line 529, in pairwise_registration
    res = gs_reg(submap_source, submap_target, self.config['lc']['registration'])
  File "/home/y/4tdisk/LoopSplat/src/gsr/solver.py", line 113, in gaussian_registration
    init_overlap = compute_overlap_gaussians(src_dict['gaussians'], tgt_dict['gaussians'], 0.1)
  File "/home/y/4tdisk/LoopSplat/src/gsr/overlap.py", line 53, in compute_overlap_gaussians
    gpu_index.add(tgt_tensor)
  File "/home/y/anaconda3/envs/loop_splat/lib/python3.10/site-packages/faiss/contrib/torch_utils.py", line 122, in torch_replacement_add
    assert hasattr(self, 'getDevice'), 'GPU tensor on CPU index not allowed'
AssertionError: GPU tensor on CPU index not allowed
Traceback (most recent call last):
  File "/home/y/4tdisk/LoopSplat/run_slam.py", line 109, in <module>
    gslam.run()
  File "/home/y/4tdisk/LoopSplat/src/entities/gaussian_slam.py", line 238, in run
    lc_output = self.loop_closer.loop_closure(self.estimated_c2ws)
  File "/home/y/4tdisk/LoopSplat/src/entities/lc.py", line 282, in loop_closure
    pose_graph, odometry_edges, loop_edges = self.construct_pose_graph(final)
  File "/home/y/4tdisk/LoopSplat/src/entities/lc.py", line 237, in construct_pose_graph
    reg_dict = self.pairwise_registration(submap_list[source_id], submap_list[target_id], "gs_reg")
  File "/home/y/4tdisk/LoopSplat/src/entities/lc.py", line 529, in pairwise_registration
    res = gs_reg(submap_source, submap_target, self.config['lc']['registration'])
  File "/home/y/4tdisk/LoopSplat/src/gsr/solver.py", line 113, in gaussian_registration
    init_overlap = compute_overlap_gaussians(src_dict['gaussians'], tgt_dict['gaussians'], 0.1)
  File "/home/y/4tdisk/LoopSplat/src/gsr/overlap.py", line 53, in compute_overlap_gaussians
    gpu_index.add(tgt_tensor)
  File "/home/y/anaconda3/envs/loop_splat/lib/python3.10/site-packages/faiss/contrib/torch_utils.py", line 122, in torch_replacement_add
    assert hasattr(self, 'getDevice'), 'GPU tensor on CPU index not allowed'
AssertionError: GPU tensor on CPU index not allowed
wandb: 

Thank you so much and have a nice day!

**Comment by Zhu-Liyuan** [comment]
Thanks for your interest in our work. You have the same issue as this [one](https://github.com/GradientSpaces/LoopSplat/issues/5). We have tested on 4090, A6000 and A100 and they all worked fine. I guess it's a hardware-related issue. You can also check the repo of [faiss](https://github.com/facebookresearch/faiss) to find out if there is a solution.
