### ISSUE TITLE
backend error :Cannot load backend 'Qt5Agg'  error

### ISSUE THREAD

**Issue by jinxxo-j** [GradientSpaces/LoopSplat#7]
hello! 
I am try to run code about your interesting works,
While running 'run_slam.py' , 
the following error occurred. Could you please let me know how to proceed

(loop_splat) jinwoo@mutalisk12:~/LoopSplat$ python run_slam.py configs/TUM_RGBD/rgbd_dataset_freiburg1_desk.yaml --input_path /home/jinwoo/LoopSplat/scripts/data/TUM_RGBD-SLAM/rgbd_dataset_freiburg1_desk --output_path /mnt/ssd1/jinwoo/loopsplat/TUM_RGBD/rgbd_dataset_freiburg1_desk                                                                         
[09-24 14:48:40] WARNING  Customized build of Open3D is not detected, to resolve this you can do:            o3d.py:11
                          pip install open3d_pycg_cpu -f https://pycg.huangjh.tech/packages/index.html                
                 WARNING  Failed to obtain monitor info!                                                     vis.py:43
Traceback (most recent call last):                                                                                    
  File "/home/jinwoo/LoopSplat/run_slam.py", line 8, in <module>                                                      
    from src.entities.gaussian_slam import GaussianSLAM                                                               
  File "/home/jinwoo/LoopSplat/src/entities/gaussian_slam.py", line 19, in <module>                                   
    from src.entities.lc import Loop_closure                                                                          
  File "/home/jinwoo/LoopSplat/src/entities/lc.py", line 25, in <module>                                              
    from src.utils.eval_utils import eval_ate                                                                         
  File "/home/jinwoo/LoopSplat/src/utils/eval_utils.py", line 12, in <module>                                         
    from evo.tools import plot                                                                                        
  File "/home/jinwoo/anaconda3/envs/loop_splat/lib/python3.10/site-packages/evo/tools/plot.py", line 33, in <module>  
    mpl.use(SETTINGS.plot_backend)                                                                                    
  File "/home/jinwoo/anaconda3/envs/loop_splat/lib/python3.10/site-packages/matplotlib/__init__.py", line 1144, in use
    plt.switch_backend(name)                                                                                          
  File "/home/jinwoo/anaconda3/envs/loop_splat/lib/python3.10/site-packages/matplotlib/pyplot.py", line 275, in switch_backend                                                                                                              
    raise ImportError(
ImportError: Cannot load backend 'Qt5Agg' which requires the 'qt' interactive framework, as 'headless' is currently running

**Comment by Zhu-Liyuan** [comment]
You are using a machine without a display. Please refer to this [solution](https://github.com/MichaelGrupp/evo/issues/534).
